# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a15a5289e006462dd50ee86183821f0157dd1a971988bcf727a8595c45c2d91a59b56b54dd9e1c35e07678a304a24408565ee44cab6c027fde120606f8eae89e

test:
  secret_key_base: c13461fcca93cd418b672579c14690fb369684c112e595cd71e7985efee74e6ba889b06ac93b03cfbd852a4fe801e3d2b5aea47297cf77f5b8b70f87549291bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
